name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    env:
      ruby-version: [3.1.2]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: "Gemfile.lock"
        bundler-cache: true
      env:
        BUNDLE_PATH: vendor/bundle

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-${{ env.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          gems-${{ runner.os }}-${{ env.ruby-version }}-
          gems-${{ runner.os }}-

    - run: bundle exec middleman build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        keep_files: true
